### ISSUE TITLE
[FEATURE] Conditional push

### ISSUE THREAD

**Issue by btorresgil** [elgohr/Publish-Docker-Github-Action#100]
**Is your feature request related to a problem? Please describe.**

Opening this to revisit #58. The feature request was dismissed because the purpose of the action is to publish, however, there are situations where the build is necessary and the push is not, depending on the branch, the event, or other circumstances.

Here is an example using the [stock docker action](https://github.com/marketplace/actions/build-and-push-docker-images) which does support conditional push:

```yml
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Publish Docker image (branch)
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ github.event.repository.name }}
          tag_with_ref: true
          push: ${{ github.event_name == 'push' }}
```

In this example, the `push:` parameter is used to only publish the image when pushing to the master or develop branches, not during a pull request. The effect is that every PR is tested to ensure it can build, but the built image is not published anywhere, and pushes to develop or master branch are built and published.

Another example use case is to build first as a test to confirm a build is possible, cache that build without publishing it, then run semantic-release to calculate the new version (tag), create the github release, and trigger the publish part. At this point the action runs a second time, using the cache from the first run to speed things up, tags the docker image with the new version determined by semantic-release, and does the publish of the image..

**Describe the solution you'd like**

With a conditional push parameter that takes a boolean, the action can cover many powerful use cases such as the example above.

**Describe alternatives you've considered**

It is possible to do this with 2 different workflows, one for push and one for pull request. Then the pull request workflow would use a different action or just a `run:` to build the image without pushing. But this requires maintaining a lot more workflow configuration and requires using different actions between them to build the docker image, so it is not a preferred solution.

Another option is to use the stock docker action, however, while that action supports conditional push, it is missing other critical features such as outputs and semver support which this action has.

Thanks for your consideration!
