### ISSUE TITLE
[BUG] Github package aka container private even for public repositories

### ISSUE THREAD

**Issue by Zethson** [elgohr/Publish-Docker-Github-Action#103]
Dear everyone,

I am not sure whether Github Packages or this workflow is the right people to complain to, but I will try it here:

I am using the following workflow:

```
on:
  release:
      types: [published]
  push:
      branches:
        - development
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: foo/bar
        username: foo
        password: '${{ secrets.CORRECTTOKEN}}'
        registry: ghcr.io
        tags: "latest"

```
It all works nicely and the package aka container is pushed where I want it to be. But even when the repository is public, the package is created private. Is there any way to make it public by default?

I assume I should bug Github Packages about this?
