### ISSUE TITLE
[BUG] tags example in README is deprecated

### ISSUE THREAD

**Issue by a1300** [elgohr/Publish-Docker-Github-Action#107]
**Describe the bug**
On the [github blog](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
) was an article published on the 1st of October 2020. This artices states that the `echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})` command will be deprecated soon. The **tags** example uses the above described, soon to be deprecated command.

Deprecated example in `README.md`
```yml
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
``` 

**To Reproduce**
Config:
`.github/worksflows/push-to-dockerhub-on-release.yml`
```yml
name: Publish develop branch to DockerHub
on:
  release:
      types: [published]
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: a1300/testnet
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        snapshot: true
        tags: "latest,develop,${{ env.RELEASE_VERSION }}"
```

This resulted for me into a deprecation warning in the command runner:

![image](https://user-images.githubusercontent.com/11912239/98460613-24c35180-21a6-11eb-99dc-984cfd3f93b9.png)

**Expected behavior**
No deprecation message.

**Additional context**
