### ISSUE TITLE
[FEATURE] `no_push: true` should not complain about missing credentials

### ISSUE THREAD

**Issue by casperdcl** [elgohr/Publish-Docker-Github-Action#110]
When `no_push: true`, don't complain about blank username/password.

Use case:

```yaml
- uses: elgohr/Publish-Docker-Github-Action@master
  with:
    name: ${{ github.repository }}
    password: ${{ secrets.DOCKER_PWD }}  # obviously blank on pull_request
    username: ${{ secrets.DOCKER_USR }}  # obviously blank on pull_request
    no_push: ${{ github.event_name == 'pull_request' }}
```

this will allow testing that the image builds on pull requests, but won't try to login. (Neater than duplicating two different versions of the block with `if: github.event_name == 'pull_request'` and `github.event_name != 'pull_request'`.)
