### ISSUE TITLE
[BUG] Not logged in to https://index.docker.io/v1/

### ISSUE THREAD

**Issue by einfallstoll** [elgohr/Publish-Docker-Github-Action#115]
**Describe the bug**
In the beginning `Login Succeeded` is logged, however, at the end of the step, the error message `Not logged in to https://index.docker.io/v1/` is thrown. This indicates that the custom registry is respected in the beginning but not in the final step, which might be a regression (#9).

**To Reproduce**

Excerpt from `workflow.yml`:
````
  publish:
    if: always()
    name: Create and Publish Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment
        run: |
          if [[ "$GITHUB_REF" == */staging || "$GITHUB_REF" == */production ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/application-${{ env.ENVIRONMENT }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: docker.pkg.github.com
          workdir: application
````

- `ENVIRONMENT` (and therefore `env.ENVIRONMENT`) are set to `development` as I work on the `develop` branch.
- `github.repository` is set to `einfallstoll/Redacted`
  - `name` resolves to `einfallstoll/Redacted/application-development`
- `github.actor` is set to `einfallstoll`
- `secrets.CR_PAT` is set to ... well ... a secret personal access token

**Expected behavior**
Docker image should be pushed to the GitHub Container Registry.
