### ISSUE TITLE
[BUG] Migrating from GitHub Packages Docker registry to GitHub Container Registry

### ISSUE THREAD

**Issue by qkdreyer** [elgohr/Publish-Docker-Github-Action#117]
**Describe the bug**
After migrating from `docker.pkg.github.com` to `ghcr.io`, I'm getting a `denied: permission_denied: write_package` error while publishing

**To Reproduce**

`workflow configuration`
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Build and publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ORG/REPO/NAME
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          workdir: NAME
          no_push: ${{ github.event_name == 'pull_request' }}
```

**Expected behavior**
Publish working

**Additional context**
I didn't have any permission denied errors while using the previous registry
