### ISSUE TITLE
Question: Action does not get the tag-information

### ISSUE THREAD

**Issue by abuhamsa** [elgohr/Publish-Docker-Github-Action#141]
Hi I'm trying to publish my dockerimage through this action.
It already works and publishes my image to dockerhub.

But I want to have it released with the tags:
- latest
- github-tag

So my Action looks like this:
```yml
name: Publish to DockerHub
on:    
  release:
      types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/xteve-lazystream
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
```

I'll push my changes to github and then creating a new release:
![image](https://user-images.githubusercontent.com/1926397/138866724-8a0fb413-0cc1-463a-b0cb-29fd3f2cfdca.png)

So I excpect that it will be published with the tags "latest" and "v.1.1.7". But the output of the action shows the following:
```log
Warning: Unexpected input(s) 'pre', valid inputs are ['entryPoint', 'args', 'name', 'username', 'password', 'registry', 'snapshot', 'default_branch', 'dockerfile', 'workdir', 'context', 'buildargs', 'buildoptions', 'cache', 'tags', 'tag_names', 'tag_semver', 'no_push']
Run elgohr/Publish-Docker-Github-Action@master
  with:
    name: ***/xteve-lazystream
    pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    username: ***
    password: ***
    tags: latest,
```

So there is an Warning about the "pre"-Part (which is used to even get the tag) and then the result is an empty string.

Am I doing this wrong or is it maybe broken for all?
