### ISSUE TITLE
[BUG] `sed` error when switching to v4 actions and built against tag

### ISSUE THREAD

**Issue by pashagolub** [elgohr/Publish-Docker-Github-Action#155]
**Describe the bug**
Error log of the [run](https://github.com/cybertec-postgresql/pg_timetable/runs/6006234983):
```
Run elgohr/Publish-Docker-Github-Action@v4
  with:
    name: cybertecpostgresql/pg_timetable
    username: ***
    password: ***
    buildargs: VERSION,COMMIT,DATE
    tag_semver: true
  env:
    VERSION: v4.6.0
    COMMIT: d1f3212955867511a3dd9361b8b828cfcb5bf75a
    DATE: 2022-04-13T12:27:07+02:00
Run $GITHUB_ACTION_PATH/entrypoint.sh
  $GITHUB_ACTION_PATH/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    VERSION: v4.6.0
    COMMIT: d1f3212955867511a3dd9361b8b828cfcb5bf75a
    DATE: 2022-04-13T12:27:07+02:00
    INPUT_NAME: cybertecpostgresql/pg_timetable
    INPUT_USERNAME: ***
    INPUT_PASSWORD: ***
    INPUT_REGISTRY: 
    INPUT_SNAPSHOT: 
    INPUT_DEFAULT_BRANCH: 
    INPUT_DOCKERFILE: 
    INPUT_WORKDIR: 
    INPUT_CONTEXT: 
    INPUT_BUILDARGS: VERSION,COMMIT,DATE
    INPUT_BUILDOPTIONS: 
    INPUT_CACHE: 
    INPUT_TAGS: 
    INPUT_TAG_NAMES: 
    INPUT_TAG_SEMVER: true
    INPUT_NO_PUSH: 

sed: -e expression #1, char 58: invalid reference \4 on `s' command's RHS
Error: Process completed with exit code 1.
```

**To Reproduce**
Workflow used:
```yml
  docker:
    if: true # false to skip job during debug
    runs-on: ubuntu-latest
    steps:
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Version strings
      id: version
      run: |
        echo "::set-output name=RELEASE_TIME::$(git show -s --format=%cI HEAD)"        

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        VERSION: ${{ github.ref_name }}
        COMMIT: ${{ github.sha }}
        DATE: ${{ steps.version.outputs.RELEASE_TIME }}       
      with:
        name: cybertecpostgresql/pg_timetable
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION,COMMIT,DATE
        tag_semver: true
```
**Additional context**
I just switched from `@master` to `@v4` action version
