### ISSUE TITLE
tag_semver is ignored for v4

### ISSUE THREAD

**Issue by pashagolub** [elgohr/Publish-Docker-Github-Action#158]
**Describe the bug**
After switching to the v4 workflow `tag_semver: true` didn't produce the tags.
Workflow run: https://github.com/cybertec-postgresql/pgwatch2/runs/6157582876
Workflow syntax: https://github.com/cybertec-postgresql/pgwatch2/actions/runs/2220212401/workflow

**Expected behavior**
On the [docker hub](https://hub.docker.com/repository/docker/cybertec/pgwatch2/tags) we can see that the `latest` tag is present but none of the `1`, `1.9`, `1.9.0`

**UPD**: I've added proper tags manually. Sorry for the confusion

Thanks in advance!

**Comment by elgohr** [comment]
The mentioned step has got the following configuration
```
- name: Publish release version to Registry
      if: ${{ !contains(github.ref_name, 'beta') }}
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        GIT_HASH: ${{ steps.version.outputs.RELEASE_VERSION }}
        GIT_TIME: ${{ steps.version.outputs.RELEASE_TIME }}     
      with:
        name: cybertec/pgwatch2${{ matrix.image }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile${{ matrix.image }}
        buildargs: GIT_HASH,GIT_TIME
        tags: "latest"
        tag_semver: true
```
It tries to use `tags` and `tag_semver`.
Like documented in https://github.com/elgohr/Publish-Docker-Github-Action#tags (` Furthermore, one of the following options can be used.`) only one of the options can be used per time. Maybe the documentation could be a little better at this point.
