### ISSUE TITLE
Publish to AWS ECR?

### ISSUE THREAD

**Issue by aron-truvian** [elgohr/Publish-Docker-Github-Action#21]
Literally just got into GitHub actions today, and saw this... it's awesome, and works great for publishing docker images to a docker repository.  

However, I have a question, which is how can I publish to AWS ECR?  The credentials I use are not in the form of a username/password, but rather an access key, and access secret.  

When I push from my computer, I can manage this by using the AWS CLI, but I am not sure how I would do that with this action.  Obviously putting the access key and secret into the username/password fields won't wok.  

Any help would be appreciated!

Thanks!

**Comment by elgohr** [comment]
Hey, this sounds really interesting.
Unfortunately this would require an interaction with the AWS API (for getting the credentials).
At the moment I'm working on a rewrite in go, as the actions seems to get more and more complex. Afterwards it should also be easy to interact with the AWS API. Until then it would really blow up the complexity of the action...

**Comment by elgohr** [comment]
Ok, I did the rewrite and in Go it's about 3 times the lines of code than in shell (+ some additional pitfalls when using the Docker SDK). In this way I will not switch to Go.

What do you think about doing that in a separate action?
Like
```
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to ECR
      id: ecr
      uses: elgohr/myNewEcrLoginAction
      with:
        username: ${{ secrets.AWS_USERNAME }}
        password: ${{ secrets.AWS_PASSWORD }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
```
