### ISSUE TITLE
Custom tags when publishing an images

### ISSUE THREAD

**Issue by vdenotaris** [elgohr/Publish-Docker-Github-Action#28]
Hi @elgohr and thank you for you amazing work.

I was looking for a mean to specify a custom tag when publishing an image via GitHub Actions.
This would help to keep a given naming convention for an already existing project.

Thanks you,
Cheers, V.

**Comment by elgohr** [comment]
Hi, you're welcome 🙂
Could you please make an example?
Are we talking about semantic versioning or something like that?

**Comment by vdenotaris** [comment]
Hi,

I am talking about the ability to explicitly define a tag directly in action.

For instance:

```
with:
  name: myDocker/repository:<tag>
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
  registry: docker.pkg.github.com
```

Where <tag> is not coming from the source repository, but defined statically.
