### ISSUE TITLE
Cannot find Repository-Name

### ISSUE THREAD

**Issue by Twonki** [elgohr/Publish-Docker-Github-Action#29]
Hey there, 

I'm having issues with the example provided in [your GithubPackage Example](https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/.github/workflows/test_integration_github.yml)

![image](https://user-images.githubusercontent.com/19567117/66260151-fca33b00-e7ba-11e9-9814-9719d38a1fff.png)

My CI/CD Actions looks mostly like your example:

``` 
  PublishToGithub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        registry: docker.pkg.github.com
        cache: true
        workdir: ./pulser
        dockerfile: BuildDockerfile
```

Reason for the changes is that I have a monorepo and this is only one component. 

The Secrets have been properly set and I am in the Github Packages Beta.

**Comment by elgohr** [comment]
Hi, could you please set `with.name` (this is not `with.username`)?

**Comment by Twonki** [comment]
Thank you ! I made some progress. 

When I just put the Image name, it added docker.io in front of it and ignored the registry. 
I then put the registry manually in front of the name, which told me that my username was missing. 

So the final name required was:

`docker.pkg.github.com/user/project/name`

That seems to be fully recognized. 

However, it tells me that the docker-client has 0 rights, and would need 'package:write'. 
![Failure4](https://user-images.githubusercontent.com/19567117/66270785-a46e4680-e857-11e9-9e53-3e8c28d85a00.png)
 
This puzzles me a little, because I actually use my real username and the login to the registry works. 

Do you have any clues how to fix this?

**Comment by turbo** [comment]
> docker-client has 0 rights, and would need 'package:write'

The PAT you use for the password must have the `package:write` permissions, just like the error says. Here's an example config from one of my projects:

```yaml
name: Build Release Docker Image

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/turbo/example/example-server
        workdir: src
        username: turbo
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
``` 

`secrets.DOCKER_PASSWORD` contains the PAT. Don't put your GitHub password in there! Generate a PAT which can only access `package:*` permissions by going to your settings -> developer settings -> Personal Access Tokens
