### ISSUE TITLE
Unable to push to ECR repository

### ISSUE THREAD

**Issue by santi6291** [elgohr/Publish-Docker-Github-Action#33]
Running the example to push to ECR but when the push command runs it doesn't seem to be pointing to the correct repository 

```
The push refers to repository [docker.io/***]
```

```
- name: Login to ECR
      id: ecr
      uses: elgohr/ecr-login-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.IMAGE_NAME_PRODUCTION }}
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ steps.ecr.outputs.registry }}
        dockerfile: Dockerfile.production
```

**Comment by elgohr** [comment]
If that doesn't help, it would be great, if you could provide feedback on what happens, if you use the Docker from https://github.com/elgohr/ecr-login-action locally.
Sadly I can't help directly, as I'm not using ECR.

**Comment by santi6291** [comment]
I see the issues, the `DOCKERNAME ` isn't prefixing the registry 
https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L12

So here when you push it doesn't have a reference to the custom registry
https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L123

I think either need to add the registry to `DOCKERNAME` if registry is defined or add it to the push  funtion

**Comment by elgohr** [comment]
Ok, so you were able to fix it by providing name with the registry?
I'm not sure about adding it in the action automatically, but I'll think about that.

**Comment by santi6291** [comment]
I think at least this should be a documented for deploying ECR or the Github registry

**Comment by elgohr** [comment]
Thank you for the feedback.
I think I'll add the registry, if the name doesn't contain it

**Comment by andrewcstewart** [comment]
Experiencing the same issue and not exactly following what the fix is?  (or is it better to wait on an incoming update?)

**Comment by santi6291** [comment]
@elgohr recently publish an update, now it will work as expected when you define the `registry` attribute, so for example,

```
- name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.5
      with:
        name: `[BUCKET]`/`[IMAGE_NAME]`
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: `[ECR_REGISTRY_ID]`.dkr.ecr.us-east-1.amazonaws.com
```
the abvove will compile your image and also push to `[ECR_REGISTRY_ID].dkr.ecr.us-east-1.amazonaws.com/[BUCKET]`/`[IMAGE_NAME]`

Hope that helps

**Comment by andrewcstewart** [comment]
Hmm, I think I'm even more confused now.  My ECR repo URI doesn't have two parts at the end:

`[ECR_REGISTRY_ID].dkr.ecr.us-east-1.amazonaws.com/[BUCKET]/[IMAGE_NAME]`

Unless that is supposed to be `[ECR_REGISTRY_ID].dkr.ecr.us-east-1.amazonaws.com/[IMAGE_NAME]:[TAG]` ??

Why is `registry: ${{ steps.ecr.outputs.registry }}` no longer valid?

My entire action looks like this:

```
name: docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to ECR
      id: ecr
      uses: elgohr/ecr-login-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.5
      with:
        name: myregistry.dkr.ecr.us-west-2.amazonaws.com/myimage
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ steps.ecr.outputs.registry }}
```
