### ISSUE TITLE
feature request: set the tag of the image as a configuration flag

### ISSUE THREAD

**Issue by Sispheor** [elgohr/Publish-Docker-Github-Action#36]
Implementation example:
```yml
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        tag: 4.0
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```
