### ISSUE TITLE
Build and publish multiple docker images 

### ISSUE THREAD

**Issue by mrturkmen06** [elgohr/Publish-Docker-Github-Action#37]
In some cases, a repository might contain multiple Dockerfiles, in this situation same credentials should be written with different `workdir` variable, as shown below
Although `tag_names` set true, for each new docker file, do I have to specify `workdir` ? 
Isn't it possible to search directories recursively and build docker images and publish them according commit tag ? (or more elegant way) Additionally,  it could be very useful if we can have `filter`, for instance, when a new dockerfile introduced the repository, the workflow should not build the images which are already exists. (in case of having recursive call)

```
 - name: Build docker image 1
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_1/files_1/
        registry: docker.pkg.github.com
        tag_names: true
    - name: Build docker image 2
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_1/files_2/
        registry: docker.pkg.github.com
        tag_names: true
    - name: Build docker image 3
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_2/files_1/
        registry: docker.pkg.github.com
        tag_names: true
```

**Comment by elgohr** [comment]
Hey, I'm not sure if that's what you really want to do.
The example given would build 3 different dockerfiles and publish/overwrite them under `myDocker/repository`.
As we can't guess the name of the image to be pushed from the dockerfile, it could be hard

**Comment by mrturkmen06** [comment]
Hej, Owh, I did not change the name sorry on given example it should be like this one, 
In this case, there will be no overwrite however I need to specify exact path of Dockerfile, recursively search actually might  help to find out newly generated dockerfiles. I can admit that recursive search could  be tricky. 

```
   - name: Build docker image 1
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository/d1f1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_1/files_1/
        registry: docker.pkg.github.com
        tag_names: true
   - name: Build docker image 2
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository/d1f2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_1/files_2/
        registry: docker.pkg.github.com
        tag_names: true
   - name: Build docker image 3
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: myDocker/repository/d2f1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: directory_2/files_1/
        registry: docker.pkg.github.com
        tag_names: true

```

However, I think, it could be very handy if we have option to provide config file which specifies image names and workdir, then this action can parse it according to given format like ; 

( then in background, action can iterate over on defined config file ) 

`.github/main.yml`
```
- name: Build docker image with config
   uses: elgohr/Publish-Docker-Github-Action@master
   with: 
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      config: "path to config file"
```

`config.json`
```
{
	{
		"workdir": "directory1",
		"name": "myDocker/repository/image1"
	}, {
		"workdir": "directory2",
		"name": "myDocker/repository/image2"
	}
}
```
