### ISSUE TITLE
Unable to publish to GitHub registry

### ISSUE THREAD

**Issue by exelban** [elgohr/Publish-Docker-Github-Action#38]
Hi. 

I used a template from README.md. And everything works fine until pushing to the registry.
But at the end of the step I see the line: `Not logged in to https://index.docker.io/v1/`.
And the image is not pushed to the registry. I see the same line [here](https://github.com/elgohr/Publish-Docker-Github-Action/commit/601d4051e257d80a7f45642e92b7bbcdaa99770c/checks?check_suite_id=274543843). So it looks like not the problem with my configuration.

But still, here's my step:
```
      - name: Publish to github registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}/cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
```
