### ISSUE TITLE
Not able to Pull from ECR to build an Image

### ISSUE THREAD

**Issue by sumitasok** [elgohr/Publish-Docker-Github-Action#40]
My Dockerfile does FROM from a private ECR repo
Docker is not able to pull from that repo.

Docker file

```
FROM 1234.dkr.ecr.***.amazonaws.com/insight/base:latest as buildStage

ADD . .
```

action file

```
    steps:
    - uses: actions/checkout@v1
    - name: Login to ECR
      id: ecr
      uses: elgohr/ecr-login-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
    - name: Build the Docker image
      run: docker build . --file ./operator-ui/deployment.Dockerfile --tag latest-staging
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: insight/in_operator-ui
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ steps.ecr.outputs.registry }}
        snapshot: true
        tag_names: true
        cache: true
```

Am I doing something wrong or is this functionality not possible in the current release?
