### ISSUE TITLE
 github docker registry :  `unauthorized: Your token has not been granted the required scopes to execute this query

### ISSUE THREAD

**Issue by badrshs** [elgohr/Publish-Docker-Github-Action#41]
ERROR : when im trying to build and push to github docker registry 

`unauthorized: Your token has not been granted the required scopes to execute this query. The 'createRegistryPackageVersion' field requires one of the following scopes: ['write:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: 
https://github.com/settings/tokens.`

and this is my file :

```
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: badrshs/*****/*****
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: badrshs/*****/*****
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PASSWORD }}
        cache: true
        registry: docker.pkg.github.com
        snapshot: true
```
i found nothing in 
https://github.com/settings/tokens.

 any help please ?

**Comment by badrshs** [comment]
I generate personal token then I edit the registry parameter
 result :
```
        name: badrshs/*****/*****
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PASSWORD }}
     registry: docker.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}

```

error : 


```
sed: bad option in substitution expression
sh: ***/XXXXXXXXX/XXX: unknown operand
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
invalid argument "docker.pkg.github.com/:_authToken=badrshs/***/XXXX/XXX" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
##[error]Docker run failed with exit code 125
```

**Comment by elgohr** [comment]
Hi,
please have a look at https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/.github/workflows/test_integration_github.yml

**Comment by elgohr** [comment]
Did it solve your problem? I would like to close this issue.

**Comment by badrshs** [comment]
sure it's not , seems like you didn't read my code or even my issue , because  you will see that i have used same code as you mention too . 
it was even copy past

**Comment by elgohr** [comment]
So, you're good to go.

**Comment by elgohr** [comment]
I guess the first error message is very clear.
Configuring `registry: docker.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}` is not the way, as you can see in the example

**Comment by elgohr** [comment]
For your initial problem, the new documentation might be helpful https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#registry

**Comment by badrshs** [comment]
the normal authentication is not working even without this package 
the only solution was  : create new token which allowed me to upload new docker image to my repository , then attach that image as 
docker.pkg.github.com/:_authToken= my token 

so maybe your solution will not work on all account , like what did i face

**Comment by elgohr** [comment]
At the moment you seem to be the only one with this issue.

**Comment by zipme** [comment]
Can we just use GITHUB_TOKEN? https://github.blog/changelog/2019-08-16-publishing-packages-from-a-github-action-to-github-package-registry/

**Comment by badrshs** [comment]
@zipme this is what i did , i couldn't publish to github without GITHUB_TOKEN,  even without this package , I mean even from windows terminal

**Comment by zipme** [comment]
@badrshs this should work for you:
```yml
...
steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: owner/repo/image-name
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
```

Note that the name should be **lowercase**
