### ISSUE TITLE
Cache Expiry Proposal

### ISSUE THREAD

**Issue by gozzarda** [elgohr/Publish-Docker-Github-Action#43]
Hi,

I noticed as per #14 that your cache option has no expiry. I was trying to figure out a way to add automatic cache expiry without needing the cron solution, and I found something that may do the trick.

The `docker history` command can give you a log of all the docker actions that were taken to create an image. Particularly with the `-H=false` option, it is possible to get timestamps for when each image/layer was created.

Unfortunately, it lists all the layers from any image your image is based on via the FROM command as well (as makes sense). This means I can't figure out a way to tell what layers we are able to rebuild or not, and hence are at risk of always triggering a full build anyway if we are based on an old image.

I don't know if you will find this information helpful, but just in case you hadn't seen this before I thought I would drop a mention here. Hopefully you can figure out a way to use this for elegant automatic cache expiry.

**Comment by elgohr** [comment]
Hey,  great suggestion, I will have a deeper look into this.

**Comment by gozzarda** [comment]
I just noticed this action: https://github.com/einaregilsson/build-number

This action provides sequential build numbers, introducing the a stateful behaviour similar to what we require. It does this by creating a GitHub ref called `build-number-N`.

We can probably do a similar thing to tag the most recent full-build. We can either embed the timestamp of the build in the ref name, or possibly use the GitHub API to look up when the ref was edited.

One way or another, this should provide the state we need to be able to tell when we should do a full build. We can possibly even provide options to invalidate cache either by number of builds or age of build.

I don't know if this idea fits your design style for this project, but it seems a promising option.

**Comment by elgohr** [comment]
I would like to change `cache` to be set to an integer, which defines the retention time in days.

If the latest pushed image extends this period, it will be rebuild.

Already checked that images, which are the same but repushed are seen as unchanged and not updated in Dockerhub.
At the moment I'm rewriting the mock, so that it can be tested.

**Comment by gozzarda** [comment]
Sounds good! Let me know if I can lend a hand somehow.

**Comment by gozzarda** [comment]
While I still think a cache expiry option is a smart feature to have, I have just found what I consider an elegant way of implementing scheduled full builds. This is based of GitHub Actions Expressions, which it turns out are more general and powerful than I thought:

```yaml
name: Publish Docker
on:
  push:
    branches:
      - master
  schedules:
    # Weekly on Sundays at 02:00
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Cache everything except scheduled builds
        cache: github.event_name != 'schedule'
```

When I get a chance I will probably make a couple of pull requests adding this example and a further note to your README.

**Comment by elgohr** [comment]
Isn't this just another way to say "please use a cron job for updating"?

**Comment by gozzarda** [comment]
Yes, but this specific trick does not appear to be well-exposed in GitHub's documentation anywhere, and is a common use case. As I say, I think a proper cache expiry feature is still a good idea, but it is worth noting this functionality is available.

**Comment by elgohr** [comment]
Maybe you want to have a look https://github.com/elgohr/Publish-Docker-Github-Action/tree/cacheRework

**Comment by gozzarda** [comment]
Unfortunately I don't think this quite works. This is the bit I wasn't about to figure out. For an example, here is the output of `docker history -H=false` for an image I maintain:

```
900690e2a1e8        2019-10-26T05:25:30Z   /bin/sh -c #(nop)  ENTRYPOINT ["/site/docker…   0                   
<missing>           2019-10-26T05:25:28Z   /bin/sh -c #(nop) WORKDIR /site                 0                   
<missing>           2019-10-26T05:25:25Z   /bin/sh -c #(nop)  EXPOSE 15102                 0                   
<missing>           2019-10-26T05:25:23Z   /bin/sh -c #(nop)  EXPOSE 15101                 0                   
...          
<missing>           2019-10-26T05:22:21Z   /bin/sh -c pip3 install --no-cache-dir --no-…   10809358            
<missing>           2019-10-26T05:21:57Z   /bin/sh -c apt-get update && apt-get install…   670666694           
<missing>           2019-10-16T23:29:01Z   /bin/sh -c #(nop)  CMD ["bash"]                 0                   
<missing>           2019-10-16T23:29:01Z   /bin/sh -c #(nop) ADD file:fdf0128645db4c8b9…   100653678           
```

Which gives a `HISTORY_TIMESTAMP` of 20191026. This all seems to be working fine so far, but the issue arises when we consider the case where I have run a previous build that **did** use the cache. `HISTORY_TIMESTAMP` is based off the topmost (and hence most recent) history entry. If my cached build updated only the last couple of layers, we would have no way of knowing based off `HISTORY_TIMESTAMP`, and wouldn't be able to notice that the lower layers were very stale.

At first it seems the simple solution to this is to use the last history entry instead, but as in my above example, the history logs include layers from the base image used in a dockerfile FROM command. In this case, my image is based off debian:stretch. You can see that debian:stretch was updated on 2019-10-16, a full ten days before I did my build. Doing a full build will not, of course, refresh these layers, as these are built and maintained by someone else. Therefore we are at risk of **always** invalidating the cache, since the base image is too old.

`docker history -H=false debian:stretch` gives the following:
```
IMAGE               CREATED AT             CREATED BY                                      SIZE                COMMENT
4f5edfdf153f        2019-10-16T23:29:01Z   /bin/sh -c #(nop)  CMD ["bash"]                 0                   
<missing>           2019-10-16T23:29:01Z   /bin/sh -c #(nop) ADD file:fdf0128645db4c8b9…   100653678           
```

As you can see, these are the oldest two layers from my image above.

I am not sure how to solve this, as we effectively need to be able to tell the age of the oldest layer that we are able to rebuild. The `docker history` command itself provides no hint as to which layers were built by us and which were inherited.

The only two solutions I have thought of are as follows, both of which have downsides:

Firstly, we could parse the Dockerfile to find if our image is based off any external image, and if so, pull it, get its history, and exclude these history lines from anywhere they appear in our history. This way we (in theory) see only the history lines for the layers we are able to build. We can then take the **oldest** of these to use for cache invalidation.

Secondly, we could do something similar to https://github.com/einaregilsson/build-number and apply a tag to the commit that the most recent full-build was made from. However, as per [the GitHub API documentation](https://developer.github.com/v3/git/refs/), you don't get data on when a reference was edited or created, so we would have to tag the commit with something like `full-build-2019-10-26`, and then parse that date to find when the last full build was performed.

I am not super happy with either of these solutions. The first one is probably my favourite, but seems like it would be very fragile, and relies on assumptions about how people use FROM statements. I will continue to think about it, but I still don't think either of these is quite ready for production use.

Hope this helps. Sorry for the wall of text.

**Comment by elgohr** [comment]
I'm not saying that this is a 100% solution (as hit rates in caches never are) ;-)
I just want to make it better than today and I think I got your concern.

When I say it in my words it would be that when the latest layer is updated more frequently than the cache time, the other layers would still never be updated. Did I got that correct? 
That's true, but I would expect people to choose this time wisely, it's still a "I know what I'm doing"-feature.

Sorry, but parsing Dockerfiles is far more than what I would like to do in this action...

**Comment by elgohr** [comment]
I had a look at the implementation of watchtower (https://github.com/containrrr/watchtower/blob/bfae38dbf8b8aaa3108a61e7c2570d97faa28c7c/pkg/container/client.go#L231).
Looks like they're simply checking the same tag for a newer image.
This makes sense for latest and other named tags, not for version pinning (e.g. Ubuntu:19.04). On the other hand pinned versions have a reason and should be updated manually, as changes might be breaking (see latest security update of alpine).
I'm thinking about trying to pull the underlying layers from history by id(if that's possible?) and resetting the cache if one of these fails.

**Comment by elgohr** [comment]
Ok, so instead of a wall of text, I did it in 3 posts :laughing: 
Looks like we can't get depending images from docker (https://stackoverflow.com/a/35312577/1406669) except when we would parse the Dockerfile, like @gozzarda suggested.
In this way we would get the name of the latest layer and could check it, but we would miss the layers that it depends on.
Just using the date turns out to be a bad idea, as images relying on `alpine` would update every time, as the image is very stable.
I would like to avoid promising a solution for people and not keeping it completly. In this way I think it could be better to improve the documentation for `cache` to include a refresh task?

**Comment by elgohr** [comment]
I updated the example in https://github.com/elgohr/Publish-Docker-Github-Action#cache
Do we want to keep it like this for now?

**Comment by gozzarda** [comment]
Sorry, but I already had an open PR #46 that demonstrated a similar but shorter example.

Up to you which you prefer, but please review my PR in case you prefer my example.

**Comment by elgohr** [comment]
Wait, maybe I didn't get it correct. You're saying that `github.event_name != 'schedule'` would be evaluated per run dynamically and would return true/false?
Had no idea that this is even possible.
If it's like that I would really like to merge.
But there would be the need of a code change as it's just validated to be set/unset at the moment, so setting it to false wouldn't have an effect.

**Comment by gozzarda** [comment]
I have tested this and it works. GitHub action expressions are evaluated each run, and can be substituted into arguments.

**Comment by elgohr** [comment]
Sadly it doesn't work (see line 5)
![image](https://user-images.githubusercontent.com/19632501/68543379-76c87000-03b6-11ea-9bf1-050229cad23e.png)
The configuration was
```yaml
name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: github.event_name != 'schedule'
```
The reason it might have worked for you is that at the moment the value of `cache` isn't validated to be a boolean but just filled. So it would cache every time...

**Comment by gozzarda** [comment]
I am away from my computer just at the moment, but I definitely got this working before. I will have to have a look later.

**Comment by gozzarda** [comment]
Just managed to give this another try, and I agree it no longer seems to work. I reimplemented it exactly as I had it working before (to the best of my memory) and now no luck. Nevermind, I guess.

I wonder if there has been a change to how expression parsing works with the public release of actions.

**Comment by elgohr** [comment]
Let's see whether we could get a response
https://github.community/t5/GitHub-Actions/Evaluate-expressions-in-with-configuration/m-p/37652

**Comment by gozzarda** [comment]
I think I might have found the issue. I don't know if they changed something or I just forgot about this, but the documentation now says to wrap expressions like so `${{ <expression> }}` to have them evaluated, so I am testing that now.

**Comment by gozzarda** [comment]
No luck. Are you able to test to see if a wrapped expression gets evaluated properly? Maybe then we can figure out how to detect the change.

**Comment by elgohr** [comment]
Confirmed.
So this would work
```yaml
name: Publish Docker
on:
  push:
    branches:
      - master
  schedule:
    # Weekly on Sundays at 02:00
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Cache everything except scheduled builds
        cache: ${{ github.event_name != 'schedule' }}
```
The only thing missing would be a check for false, as https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L113 just checks for being set.
