### ISSUE TITLE
Cache option not working in PR merges

### ISSUE THREAD

**Issue by alexsotocx** [elgohr/Publish-Docker-Github-Action#47]
Hello,

I have been experiencing issues with the cache option. It works fine on the `master` branch, it uses the cache without any problem, but in the PR(The same of master) workflow we build an image and it rebuilds it entirely even if the layer didn't change.

# Here the workflow

```yaml
# ...
docker:
    name: docker build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@master
    - name: Build and publish docker image to GCP Container Registry
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: image_name
        username: <user>
        password: <password>
        dockerfile: Dockerfile
        cache: true
```

# Here the Dockerfile

```Dockerfile
FROM ruby:2.4-slim
WORKDIR /app

# Copy gemfile
ADD Gemfile* /app/

# Dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libv8-dev \
    tzdata \
    libmagickwand-dev \
    libpq-dev && \
    gem install bundler && \
    bundle install --deployment -j4 --retry 3 && \
    rm -rf /usr/local/bundle/cache/*.gem && \
    rm -rf /app/vendor/bundle/ruby/2.4.0/cache/*.gem && \
    find /app/vendor -name "*.c" -delete && \
    find /app/vendor -name "*.o" -delete

# Add the Rails app
ADD . /app

# Precompile assets
RUN bundle exec rake assets:precompile

# Remove unused files && Create app user and give access to the required files
RUN \
  rm -rf tmp/cache app/assets vendor/assets lib/assets spec test && \
  addgroup -gid 1000 -system app && \
  adduser -u 1000 --system --ingroup app app && \
  chown -R  app:app /app && \
  chown -R  app:app /usr/local/bundle/

USER app

# Expose Puma port
EXPOSE 3000

CMD [ "bundle" ]
```

In my local pc it works perfectly and it uses the cache.
