### ISSUE TITLE
Question: Can you tag as 'latest' AND by tag name?

### ISSUE THREAD

**Issue by artis3n** [elgohr/Publish-Docker-Github-Action#52]
I am using your (excellent) action here: https://github.com/artis3n/docker-ubuntu1804-ansible/blob/master/.github/workflows/deploy.yml

My desired steps:

- Publish to Docker with the tag of the release
    - Your `tag_name` option picks up the right tag since this workflow is triggered on a release publication
- At the same time, publish to Docker with the `latest` tag
    - Docker caches my layers so the second invocation of this action runs very quickly, but it would be nice if I didn't have to duplicate it.
- Do the same two steps for GitHub package registry
    - Unrelated except that it would be nice to cut down on the duplication

I suppose what I'm asking for is support for multiple tags in one invocation of this action. Is that something you are interested in supporting? The only related issue I see is #16 which was resolved for their use case by a snapshot tag, which would not apply here.

In case the code in the link above changes, this is the current workflow I am using, where I'd like to have 2 steps (one for Docker, one for GitHub) as opposed to 4:

```yaml
    - name: Deploy the Docker image to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/docker-ubuntu1804-ansible/docker-ubuntu1804-ansible
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_names: true

    - name: Deploy the Docker image to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/docker-ubuntu1804-ansible
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tag_names: true
    
    - name: Deploy the Docker image to GitHub Package Registry (latest tag)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/docker-ubuntu1804-ansible/docker-ubuntu1804-ansible
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

    - name: Deploy the Docker image to Docker Hub (latest tag)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/docker-ubuntu1804-ansible
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
```

**Comment by elgohr** [comment]
Happy to hear that you seem to be happy with the action.
I don't know whether this wouldn't lead to confusion regarding the current deployed `latest` at a time. Some people do matrix builds by branch and it would really be hard to find out which of these branches is the current master. In addition there would be a higher chance for overriding master via multiple "racing" branches. In this way we would rely more on a correct configuration around the action itself.
But I saw a few requests for a "push to master" flag. Probably this could help you too

**Comment by artis3n** [comment]
> Some people do matrix builds by branch and it would really be hard to find out which of these branches is the current master

That is a fair point, not sure how it could be reconciled with this request

**Comment by elgohr** [comment]
Me neither, that's why it's not there at the moment :laughing:

**Comment by wperron** [comment]
I'm also looking for something similar, sort of in-between the current `tag_names` and `snapshot` parameters.

Maybe giving the option to specify the different tags to use by passing them directly as inputs would be enough? it transfers some of the complexity back to the user, but it makes the implementation of the action much simpler since it no longer has to choose how to name the tag. For people using matrix builds with branch name, I would expect them to understand the complexity of their build better than anyone else, so giving them the flexibility of choosing their tag name pattern might actually be something nice.

at the end of the day what I really want is more control over the tags that come out of my builds! 😛

**Comment by elgohr** [comment]
I'm thinking about introducing something like 
```
with:
  tags: latest,another,...
```
Where people can define their own tags, which would be taken instead of every other tag.

**Comment by artis3n** [comment]
That could work. My use case would then be covered by `tags: latest, ${{ github.ref }}`

**Comment by elgohr** [comment]
Turns out to be not that easy. Which tag would you pull for https://github.com/elgohr/Publish-Docker-Github-Action#cache ?
Pulling every tag will be non-reproducible for sure...

**Comment by artis3n** [comment]
@elgohr How does `cache` and `tag_names`/`snapshot` currently resolve?

Also, the multiple tag support could be mutually exclusive with `cache`, although of course we'd probably want to avoid that.

**Comment by elgohr** [comment]
At the moment there's always one tag (which is variable) and the maybe an additional snapshot-tag. In this way the "main"-tag is known always. When using tags there wouldn't be a main tag.

**Comment by elgohr** [comment]
I'm thinking about caching from the first tag in `tags`

**Comment by artis3n** [comment]
What about adding a `cache_tag` parameter? Defaults to the value of `tags` if it's 1 element (or uses `tag_names`/snapshots or whatever as it currently does), otherwise errors with a "can't determine cache tag" and a note to specify which of the `tags` specified you'd like to use in `cache_tag`. Maybe that's over-engineering the problem.

**Comment by elgohr** [comment]
> Maybe that's over-engineering the problem.  
Guess so 😀 
Maybe we could start with caching the first image and maybe introducing `CACHE_FROM` as an array later.
I don't want to deprecate `CACHE` n favor of something like `CACHE_FROM`, as it still has a way to build without cache regularly.

**Comment by matthewfeickert** [comment]
> I'm thinking about introducing something like
> 
> ```
> with:
>   tags: latest,another,...
> ```
> 
> Where people can define their own tags, which would be taken instead of every other tag.

Hi. This would also be useful in general to [us](https://github.com/scikit-hep/pyhf). We have a [GHA workflow that creates bumpversion releases for our Python library](https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/tag.yml), but it would be nice to be able to use your Action to be able to build a single Docker image, and then tag it multiple times, and then push to the registry. 

So maybe something that from our end looks like:

```yaml
  tagdocker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.2.0
    - name: Publish Tagged Docker Image to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pyhf/pyhf
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        buildoptions: "--compress"
        tags: latest, latest-stable, ${{ env['NEW_TAG'] }}
```

(where `${{ env['NEW_TAG'] }}` is something we obviously resolve ourselves.)

It seems that you already have given this some thought

> Maybe we could start with caching the first image and maybe introducing `CACHE_FROM` as an array later.
> I don't want to deprecate `CACHE` in favor of something like `CACHE_FROM`, as it still has a way to build without cache regularly.

You've designed a very nice tool and done lots of work to do so (thank you!), so if there are things that we can help with on this end please let us know. We don't want to pester or be annoying if you already have a plan, but if we can be helpful we'd like to be.

**Comment by elgohr** [comment]
Thank you for the suggestions and warm words 🙂
There are some basic parts (e.g. bourne shell doesn't support arrays) where I have to do a little more thinking. I don't want the image to grow just because of that. There're already ideas and I'm almost halfway in implementation. I think we'll have it within this decade 🤪

**Comment by matthewfeickert** [comment]
> There are some basic parts (e.g. bourne shell doesn't support arrays - arrays are used within tests as bats builds on bash) where I have to do a little more thinking.

Oops! Yup, sorry I was forgetting that this is being run in Alpine (sorry for the Bash above).

> There're already ideas and I'm almost halfway in implementation. I think we'll have it within this decade 🤪

Awesome! :wink:

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action#tags
See https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.12

**Comment by luigi311** [comment]
With this [stacked overflow](https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions) I was able to create an env variable and call it in the tags string 

Add this as a step  
```
- name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
```
  
Use this tag in the publishing step  
```
tags: "latest,${{ env.RELEASE_VERSION }}"
```

**Comment by aasensiomtd** [comment]
Hi! I couldn't get the tag to accept a custom parameter. I tried some X response and it didn't work. I'm initiated in Github actions so I'm not sure if I'm doing anything wrong. I share the step: 

`    steps:
      - uses: actions/checkout@master
        env:
          SHA8: ${GITHUB_SHA::8}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: spotlightapp/spotlight-frontend-dashboard
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: DBHOST=${{secrets.K8_POSTGRES_IP}}
          dockerfile: Dockerfile
          tags: "latest, ${{SHA8}}"`

I've also tried `tags: "latest, ${SHA8}"``, `tags: "latest, SHA8"``, `tags: "latest", ${SHA8}` and so on... I'm out of ideas! 

Any suggestion?

**Comment by artis3n** [comment]
@aasensiomtd try `${env.SHA8}` or `$SHA8`

**Comment by aasensiomtd** [comment]
Hi @artis3n, thanks for answer. With `${{env.SHA8}}` didn't work. There is no error, latest tag is just pushed to dockerhub repository.

With `$SHA8` I have the next error: 
```
Login Succeeded
invalid argument "***/spotlight-frontend-dashboard:$SHA8" for "-t, --tag" flag: invalid reference format
```

**Comment by luigi311** [comment]
@aasensiomtd 
Do this 

```
steps:
      - uses: actions/checkout@master
        env:
          SHA8: ${GITHUB_SHA::8}
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA::8})
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
            name: spotlightapp/spotlight-frontend-dashboard
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            buildArgs: DBHOST=${{secrets.K8_POSTGRES_IP}}
            dockerfile: Dockerfile
            tags: "latest,${{ env.RELEASE_VERSION }}"
```
