### ISSUE TITLE
[Question] can't add file into image 

### ISSUE THREAD

**Issue by appleboy** [elgohr/Publish-Docker-Github-Action#55]
My Dockerfile:

```
FROM plugins/base:linux-amd64

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="example-api" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

EXPOSE 8080

COPY release/linux/amd64/example-api /bin/

HEALTHCHECK --start-period=2s --interval=10s --timeout=5s \
  CMD ["/bin/example-api", "health"]

ENTRYPOINT ["/bin/example-api"]
CMD ["server"]
```

GitHub Action Flow:

```yaml
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    # container: 'golang:1.13'
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build binary
      run: |
        go build -v -tags 'sqlite sqlite_unlock_notify' -ldflags "-extldflags -static -X github.com/appleboy/example-api/pkg/version.Version=`git rev-parse --short "$GITHUB_SHA"` -X github.com/appleboy/example-api/pkg/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`" -a -o release/linux/adm64/example-api ./cmd/example-api
        ./release/linux/adm64/example-api -h
        pwd
        ls -al
        ls -al ./release/linux/adm64/example-api

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: appleboy/example-api
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        dockerfile: docker/example-api/Dockerfile.linux.amd64
```

I don't know why I can' add binary from `github/workspace`.

```
Step 8/11 : COPY release/linux/amd64/example-api /bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder706841577/release/linux/amd64/example-api: no such file or directory
##[error]Docker run failed with exit code 1
```
