### ISSUE TITLE
[BUG] unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by maxisme** [elgohr/Publish-Docker-Github-Action#68]
**Describe the bug**
You can see the output [here](https://github.com/maxisme/notifi-backend/runs/448907553?check_suite_focus=true):

> WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
> 
> Login Succeeded
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
> ##[error]Docker run failed with exit code 1

**To Reproduce**
I am using this code to publish to my github registry.
```
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          context: ${{ github.workspace }}
```

Which equates to:
```
  with:
    name: maxisme/notifi-backend
    username: maxisme
    password: ***
    registry: docker.pkg.github.com
    context: /home/runner/work/notifi-backend/notifi-backend
```

**Expected behavior**
To upload to my github registry.

**Additional context**
N/A

Any ideas what I am doing wrong? 🙂
