### ISSUE TITLE
tags and tag_semver are mutually exclusive

### ISSUE THREAD

**Issue by artis3n** [elgohr/Publish-Docker-Github-Action#70]
**Describe the bug**
I use this GitHub Action [here](https://github.com/artis3n/kali-artis3n/blob/master/.github/workflows/deploy.yml#L36), and recently tried to incorporate `tag_semver` into my deploy. What I would like is `1`, `1.2` and `1.2.1` tagged, as well as `latest` updated. Instead, it looks like it only used `tag` and just deployed `latest`.

My [deploy](https://github.com/artis3n/kali-artis3n/runs/496913835?check_suite_focus=true) ran 22 hours ago as of this post, but [my Docker Hub tags](https://hub.docker.com/r/artis3n/kali/tags) were last updated 6 days ago (with the exception of latest, which was updated 22 hours ago).

I see `tag_semver` defaults to `latest` if the tag isn't properly formatted for semver. The [releases](https://github.com/artis3n/kali-artis3n/releases) follow proper semver with a `v` in the tag name, which should be fine.

**To Reproduce**
Run the workflow step:
```yaml
    - name: Deploy the Docker image to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tags: "latest"
        tag_semver: true
```

**Expected behavior**
The docker image is published with major, major.minor, major.minor.patch, and latest tags. Currently, `tags` is chosen presumably because it is first and that is all that is used.

**Additional context**
I'm assuming the `if/elif` setup [here](https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L71) is what causes `tags` to be used but not `tag_semver`. Instead of `elif`s, perhaps some or all of these should be individual `if`s. That would allow users to mix+match whichever tag options they want.

**Comment by elgohr** [comment]
This is correct, as `tags` hands over the full control and responsibility to you.
By the way, the given configuration would push every change on every branch to latest. I don't think that this is what you wanted.

**Comment by artis3n** [comment]
The trigger for this workflow is 

```
on:
  release:
    types:
      - published
```

so it only triggers the released tag (which would always be master).

**Comment by artis3n** [comment]
Is there a way to reconcile `tag_semver` with adding a `latest` tag?

**Comment by elgohr** [comment]
Sorry, maybe I don't get it. `latest` is no valid semver (https://semver.org/). If you also listen on push, this could be a way

**Comment by artis3n** [comment]
Right. I'd love to update my semver tags on a release, as well as update my `latest` tag. I can invoke the task twice since the layers will be cached if we don't want to support this in the Action, otherwise I was hoping I can set both `tag_semver` with additional custom `tags`.

**Comment by elgohr** [comment]
At the moment the default Docker tag for tagged commits is latest (which makes this situation a little more complex).
People might want to "switch worlds" to semver or turn it around and use the commit tag as the docker tag.
Having travelers between these worlds would result in an explosion of complexity to this action and, like in semver, might not meet the individual requirements.

I also had a look at @sergeysova s version, which would be an idea. Nevertheless it would prevent full control over the tags, as the given `tags` would just extend the translated tags, not override them.

In this way I would ask you to invoke it twice, sorry.

**Comment by artis3n** [comment]
That is fair - I'd ask that the tag behavior be documented more clearly in the readme and explained that only one tag input parameter should be used at a time.

**Comment by elgohr** [comment]
Otherwise there had to be tags like `without_default`, which I would like to avoid.

**Comment by artis3n** [comment]
Feel free to close this issue or leave it open as a documentation improvement

**Comment by elgohr** [comment]
Will leave it open for improving the documentation

**Comment by sergeysova** [comment]
I want to have behavior like this:
1. When I push to master, GitHub action push the latest tag and trigger deploy to dev
2. When I push tag, GitHub action push the semver tags `0` `0.1` `0.1.5`

**Comment by elgohr** [comment]
This is already possible.

**Comment by sergeysova** [comment]
@elgohr can you show me example?

**Comment by elgohr** [comment]
```
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
```

as tagging a commit is just another push.

**Comment by elgohr** [comment]
Just keep in mind that `00.10.1.5` is not a valid semver

**Comment by sergeysova** [comment]
@elgohr Can `tag_semver` be used with `snapshot` ?

**Comment by elgohr** [comment]
Yes

**Comment by matthieugouel** [comment]
Hello, 
I try to have the behavior as @sergeysova described.
I have this following configuration : 

```
name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matthieugouel/myimage
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./dockerfiles/Dockerfile-agent
          tag_semver: true
```

When I push, I have the different semver tags (for instance `0`, `0.1`, `0.1.2`) but the `latest` tag is not updated. Do I do something wrong ? 

Thanks,
Matthieu.
