### ISSUE TITLE
[FEATURE] Getting fancy with tag prepends / postpends

### ISSUE THREAD

**Issue by artis3n** [elgohr/Publish-Docker-Github-Action#71]
**Is your feature request related to a problem? Please describe.**

I have a multi-stage build and I'd like to build my Dockerfile with different tags targeting different stages.

**Describe the solution you'd like**

```bash
docker build -t myimage --target base .
```

```bash
docker build -t myimage --target extrathing .
```

Let's say I have a Dockerfile with a base image and a second stage doing additional things, that increases the size of the image substantially. To support use cases where people don't need the extra stuff added in the second stage, I'd like to tag my image with and without the second stage.

My idea is:

```
myhub/myimage:latest
myhub/myimage:latest-no-extrathing

myhub/myimage:1.2.0
myhub/myimage:1.2.0-no-extrathing
```

With the `tags` input parameter I can specify `latest` and `latest-no-extrathing` myself, however I cannot do this when taking advantage of the `tag_semver` input parameter. I would love to be able to specify a postpend (or prepend) to add to the tag.

Idea:

```yaml
   - name: Deploy the Docker image to GitHub Package Registry - Semver (Wordlists)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali-artis3n/kali
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        buildoptions: "--target wordlists"
        tag_semver: true
   
   - name: Deploy the Docker image to Docker Hub - Semver (Base)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        buildoptions: "--target base"
        tag_semver: true
        tag-postpend: "-no-wordlists" # This creates final semver tags like 1.2.0-no-wordlists
```

**Describe alternatives you've considered**

Only tag `latest` with the `-no-extrathing`, or forego `tag_semver` to do all the semver tagging myself in my workflow file to add the `-no-extrathing`. The former is what I'm going with for now because I do not want to do the latter.

**Additional context**
How horrible is my imagination here.
