### ISSUE TITLE
[BUG] Unable to Build and Push Docker image with Maven build

### ISSUE THREAD

**Issue by vinodjayachandran** [elgohr/Publish-Docker-Github-Action#77]
I am a novice with GitHub Actions. I have the below DockerFile

    FROM openjdk:8-jdk-alpine
    RUN addgroup -S spring && adduser -S spring -G spring
    USER spring:spring
    ARG JAR_FILE=target/*.jar
    COPY ${JAR_FILE} app.jar
    ENTRYPOINT ["java","-jar","/app.jar"]

I am trying to use the GitHub Action [Publish Docker][1] and below is my action code

```
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

The build fails with below error

    Step 5/6 : COPY ${JAR_FILE} app.jar
    COPY failed: no source files were specified

I assume it's not able to get the jar file under target folder. Should I add another step for Maven Build before docker build ensure target folder is generated with Jar. 

I updated my action as below yet same error

    name: Build and push Docker images
    
    on:
      push:
        branches: [ master ]
      pull_request:
        branches: [ master ]
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Build with Maven
            run: mvn -B package --file pom.xml
          - uses: actions/checkout@master
          - name: Publish to Registry
            uses: elgohr/Publish-Docker-Github-Action@master
            with:
              name: vinodjayachandran/spring-boot-docker
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

  [1]: https://github.com/marketplace/actions/publish-docker
