### ISSUE TITLE
[FEATURE] Publish this repository's releases to Docker hub

### ISSUE THREAD

**Issue by richardsimko** [elgohr/Publish-Docker-Github-Action#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This repository's releases being published to the Docker Hub. 

**Describe alternatives you've considered**
Currently I can either have each GH action run build this repository (Waste of build minutes and time) or use the `latest` tag from here https://hub.docker.com/r/lgohr/publish-docker-github-action (Dangerous due to risk of breaking changes).

**Additional context**
I'm happy to submit a PR for this, I would presume it would be as easy as adding a new action that runs on tag/release events.

**Comment by elgohr** [comment]
Hey, I guess this could go the same way as https://github.com/elgohr/ecr-login-action/issues/6 :)

**Comment by richardsimko** [comment]
Yeah, publishing it to GH packages would of course work just as well but as I understand it that's currently not available?

**Comment by elgohr** [comment]
We could also have an action with a Dockerfile that just has `FROM external:latest`.
It would speed things up and make releasing for me more easy, as this had to be released once (manual process) and afterwards it would pick up latest images. But it would also mean a lack of trust, as people couldn't pin versions and had to trust me that I'm not doing something evil on that latest image.
In this way to me it's an issue in the way actions are released and should be addressed to GitHub.

**Comment by richardsimko** [comment]
Wouldn't something like this work in the mean time though?

```yml
name: Release to Docker Hub
release:
  types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lgohr/publish-docker-github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        labels: ${{ github.ref }}
```

This will use the `release` [event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release) in Github to also push to Docker hub with the same label.
