### ISSUE TITLE
self-hosted: unable to evaluate symlinks in Dockerfile path

### ISSUE THREAD

**Issue by synixebrett** [elgohr/Publish-Docker-Github-Action#79]
**Describe the bug**
Unable to get it working on a self-hosted runner

**To Reproduce**
```yaml
name: Publish Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: synixebrett/test-image
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

```
Login Succeeded
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
```
