### ISSUE TITLE
Latest commit broke pipeline[BUG]

### ISSUE THREAD

**Issue by ebwinters** [elgohr/Publish-Docker-Github-Action#85]
**Describe the bug**
Action doesn't work using github secrets password

**To Reproduce**
```yaml
with:
          name: name-here
          username: plaintext-username
          password: ${{ secrets.Docker_Token }}
          tags: "latest"
```

**Expected behavior**
Sign in works with username and secret token

**Additional context**
`Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password` is the log

The action was working 6 hours ago, but after latest commit to this repo, it breaks. Please revert
