### ISSUE TITLE
Unable to build image and publish

### ISSUE THREAD

**Issue by jhoward321** [elgohr/Publish-Docker-Github-Action#9]
Following the readme, I am trying to build and publish an image to dockerhub. I'm using the custom image feature, but it never is able to build. Inside my repository I have a directory Dockerfiles with multiple dockerfiles inside. So I am passing in dockerfile optional arg as Dockerfiles/Dockerfile for one of my build steps and get the following error.

```
/usr/bin/docker run --name fe0f5d4bdcde88084e97b242923b2f722351_c7a201 --label 29fe0f --workdir /github/workspace --rm -e INPUT_ARGS -e INPUT_SNAPSHOT -e INPUT_DOCKERFILE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/hop/hop":"/github/workspace" 29fe0f:5d4bdcde88084e97b242923b2f722351 ***/hop
 unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
An image does not exist locally with the tag: ***/hop
The push refers to repository [docker.io/***/hop]
##[error]Docker run failed with exit code 1
```

**Comment by jhoward321** [comment]
This is my job in my pipeline if its useful.

```
build-hop-docker:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and upload image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          args: jhoward6/hop
          snapshot: true
          # imagename: hop
          dockerfile: Dockerfiles/Dockerfile
      - name: Logout from Docker Hub
        run: docker logout
```

**Comment by elgohr** [comment]
Could you please try again?
https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.3

**Comment by jhoward321** [comment]
The image can build now, but it doesn't seem to publish. Here's the output. I logged in the step before successfully, so I should have access to push. Below the output is the job.

```
Successfully built 1ed9ee193416
Successfully tagged ***/hop-identity:ISS63-setup-dev-identity
 Successfully tagged ***/hop-identity:b59fc31dec647a67237c30bf5d547faa8ba6910c
The push refers to repository [docker.io/***/hop-identity]
92bd223ed162: Preparing
9b651e9c9692: Preparing
436ce455c5ab: Preparing
cf9653f2b9ca: Preparing
f1b5933fe4b5: Preparing
denied: requested access to the resource is denied
The push refers to repository [docker.io/***/hop-identity]
```

```
build-identity-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and upload image
      uses: elgohr/Publish-Docker-Github-Action@e541342

      with:
        args: jhoward6/hop-identity
        snapshot: true
        dockerfile: Dockerfiles/Dockerfile.Identity
    - name: Logout from Docker Hub
      run: docker logout
```
