### ISSUE TITLE
[BUG] buildoptions missing from action.yml

### ISSUE THREAD

**Issue by artis3n** [elgohr/Publish-Docker-Github-Action#90]
**Describe the bug**
I get the following ~error~ warning when using this action from master:

```
 ##[warning]Unexpected input 'buildoptions', valid inputs are ['entryPoint', 'args', 'name', 'username', 'password', 'registry', 'snapshot', 'dockerfile', 'workdir', 'buildargs', 'cache', 'tags', 'tag_names', 'tag_semver']
```

According to [the README](https://github.com/elgohr/Publish-Docker-Github-Action#buildoptions), this is a supported option.

**To Reproduce**

<https://github.com/artis3n/kali-artis3n>

```yaml
- name: Deploy the Docker image to GitHub Package Registry - Semver (Wordlists)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali-artis3n/kali
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        buildoptions: "--target wordlists"
        tag_semver: true
```

**Expected behavior**
The image builds and is deployed to the registry.

**Additional context**
Will be filing a PR to add the parameter to `action.yml`. Adding this issue in case the PR is not sufficient for whatever reason.
