### ISSUE TITLE
[FEATURE] Allow specifying which branch will result in "latest" tag

### ISSUE THREAD

**Issue by stefandesu** [elgohr/Publish-Docker-Github-Action#96]
**Is your feature request related to a problem? Please describe.**
There has been this movement recently to rename `master` branches into something else, like `main`. Currently, this Action has `master` hardcoded to result in the "latest" tag.

**Describe the solution you'd like**
An argument to change which branch will result in the "latest" tag.

**Describe alternatives you've considered**
It might be possible to achieve this already with a specific configuration of the Action. Currently, this is my configuration:
```yml
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: stefandesu/docker-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        tag_semver: true
```
When using the `master` branch as the branch were releases are being merged into, this config does EXACTLY what I want (which is a tag for each branch, semver tags, and having the latest release as `latest`). When renaming `master` to `main`, it will push to the `main` tag, but not to the latest tag anymore. If it's possible to achieve the same effect with the current version of the Action, I'd be satisfied as well.

Edit: I guess a simple (but maybe not elegant) solution would be to have a different action only for the branch that is supposed to result in "latest" and manually specify "latest" there.

**Additional context**
My test repository is https://github.com/stefandesu/docker-test (where I just renamed `master` into `main`).

Thanks!

**Comment by stefandesu** [comment]
Update: My current workaround is the following configuration:

```yml
name: Publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: stefandesu/docker-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        tag_semver: true
  publish-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: stefandesu/docker-test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        tags: latest
```

Maybe you'll still consider implementing what I suggested, as it seems easy to do. Otherwise, feel free to close the issue as `wontfix`.
