### ISSUE TITLE
[BUG] Push fails

### ISSUE THREAD

**Issue by yspreen** [elgohr/Publish-Docker-Github-Action#97]
`denied: requested access to the resource is denied`

If I manually push my image, it works fine. The action produces this error. I'm using an access token to access one of my organization's repos.

```yaml
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: bromberglab/bio-node-docs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```
